### PR TITLE
George logo

### PR DESCRIPTION
**Pull request by georgezsiga**

### CODE REVIEW

**Comment by adamgyulavari** [comment]
@georgezsiga this has 24 files changed. for a logo replacement there should be 2.

**Comment by adamgyulavari** [comment]
and also there are conflicts

**Comment by georgezsiga** [comment]
There is so many files changed because there are new files for every resolution for the icon. and deleted old icons.. that is why the so many file changes

**Comment by adamgyulavari** [comment]
@georgezsiga check the changes tab here. you can see that there are new activities in this change. thats part of a different story and should be a different pull request

**Comment by georgezsiga** [comment]
you can delete this...

**Pull request closed without merging**
